name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('SRC/**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore
        working-directory: SRC

      - name: Extract Version
        id: vars
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: SRC

      - name: Pack
        run: dotnet pack --no-build --configuration Release --include-symbols --include-source /p:PackageVersion=${{ steps.vars.outputs.VERSION }} /p:Version=${{ steps.vars.outputs.VERSION }}
        working-directory: SRC

      - name: Publish to NuGet
        run: |
          dotnet nuget push SRC/**/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push SRC/**/bin/Release/*.snupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
